name: Deploy using GitHub Page

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v1

      - name: deploy docs
        uses: ./
        with: remote_url:https://github.com/Fem-Fem//a-small-store.git
